### ISSUE TITLE
MariaDB is not installed during provisioning

### ISSUE THREAD

**Issue by ulrikkold** [Tuurlijk/TYPO3.Homestead#12]
```
TASK: [mariadb | Install MariaDB Packages] ************************************ 
failed: [default] => (item=mariadb-server,python-mysqldb) => {"failed": true, "item": "mariadb-server,python-mysqldb"}
stderr: E: Unable to correct problems, you have held broken packages.

stdout: Reading package lists...
Building dependency tree...
Reading state information...
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 mariadb-server : Depends: mariadb-server-10.1 (= 10.1.4+maria-1~trusty) but it is not going to be installed

msg: '/usr/bin/apt-get -y -o "Dpkg::Options::=--force-confdef" -o "Dpkg::Options::=--force-confold"   install 'mariadb-server'' failed: E: Unable to correct problems, you have held broken packages.
```

I have major problems when I try to install mariadb during provisioning. There seems to be more reports about this, but I have not been able to find a solution for this yet: https://mariadb.atlassian.net/browse/MDEV-5977 and https://groups.google.com/forum/#!topic/erpnext-developer-forum/aM2QkLWBgL8

Do you have a clue? I have tried to follow the procedures in both the above links, but haven't had any luck so far. It may be that my server-fu is failing me.

**Comment by Tuurlijk** [comment]
Does it fail each time? Even on a clean install? `vagrant destroy && vagrant up` ?

**Comment by ulrikkold** [comment]
every time.

**Comment by ulrikkold** [comment]
Doh. wrong button

**Comment by ulrikkold** [comment]
Using a different mirror for mariaDB helped. I picked one from this list: https://downloads.mariadb.org/mariadb/repositories/#mirror=nluug&distro=Ubuntu&distro_release=trusty--ubuntu_trusty&version=5.5

I'll close this issue (again).

**Comment by boscowitch** [comment]
had the same issue different mirror works fine ... when will this be fixed in the current release

EDIT: oh nevermind seems like it was caused from an old global homestead install in the path instead of the new local one

**Comment by Tuurlijk** [comment]
Can you create a pull request?
