### ISSUE TITLE
Missing user _cli_lowlevel

### ISSUE THREAD

**Issue by ulrikkold** [Tuurlijk/TYPO3.Homestead#13]
```
TASK: [typo3 | typo3_console cache warmup] ************************************ 
failed: [default] => (item={'key': '7.1.cms.local.typo3.org', 'value': '7.1.*'}) => {"changed": true, "cmd": ["/var/www/7.1.cms.local.typo3.org/typo3cms", "cache:warmup"], "delta": "0:00:01.696698", "end": "2015-04-17 13:04:43.994085", "item": {"key": "7.1.cms.local.typo3.org", "value": "7.1.*"}, "rc": 3, "start": "2015-04-17 13:04:42.297387", "warnings": []}
stderr: ERROR: No backend user named "_cli_lowlevel" was found!
```

Is this supposed to happen? I'm guessing there should have been an SQL-file with a set of standard users, which should have been imported before warming up the cache? Or is the typo3_console feature not complete yet?

**Comment by Tuurlijk** [comment]
I can't reproduce this. I did a fresh build of a box this morning without any issues.

**Comment by Tuurlijk** [comment]
I have seen this happen when re-running composer on a site with an existing database. In this case it may help to remove both the database and the web files for that site. Then re-deploy.

**Comment by ulrikkold** [comment]
I'll try that when I find the time.

søn. 19. apr. 2015 10.27 skrev Michiel Roos notifications@github.com:

**Comment by Tuurlijk** [comment]
Please re-open if this is still an issue ;-)
