### ISSUE TITLE
Installing in Ubuntu 14.04

### ISSUE THREAD

**Issue by pruss** [Tuurlijk/TYPO3.Homestead#14]
On Ubuntu ansible version is 1.5.4.
Run ansible you must sudo because files will be created in /etc/ansible/roles
So correct description:

sudo ansible-galaxy install -r requirements_pre-1.8.txt
cd roles
sudo mv /etc/ansible/roles/nbz4live.php-fpm php-fpm 
sudo mv /etc/ansible/roles/jdauphant.nginx nginx
sudo mv /etc/ansible/roles/tersmitten.composer composer
sudo mv /etc/ansible/roles/laggyluke.nodejs nodejs
sudo mv /etc/ansible/roles/f500.memcached memcached

**Comment by Tuurlijk** [comment]
Thx! I updated the documentation.

**Comment by pruss** [comment]
Hallo Michiel,

I've no idea if this is correct also for other Linux distributions. But 
for Debian based it should work.

Peter.

Michiel Roos schrieb am 21.04.2015 um 19:46:
