### ISSUE TITLE
Vagrant on Ubuntu 14.04

### ISSUE THREAD

**Issue by pruss** [Tuurlijk/TYPO3.Homestead#15]
$ vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
There are errors in the configuration of this machine. Please fix
the following errors and try again:

vm:
- The box 'ubuntu/trusty64' could not be found.

This is due to an old version of vagrant. To solve this followed instruction found here https://github.com/fideloper/Vaprobash/issues/322:
$ sudo apt-get remove vagrant
and installed version from here https://www.vagrantup.com/downloads

**Comment by Tuurlijk** [comment]
Thx, I updated the README to reflect this.
