### ISSUE TITLE
Bugreport: "ansible/roles/php-fpm" not found

### ISSUE THREAD

**Issue by marble** [Tuurlijk/TYPO3.Homestead#16]
**What may be the reason for this problem?**

On "vagrant up" I get:

<pre>
==> default: Running provisioner: ansible...
ERROR: cannot find role in /home/marble/htdocs/TYPO3.Homestead/roles/php-fpm or /home/marble/htdocs/TYPO3.Homestead/php-fpm or /etc/ansible/roles/php-fpm
Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.
</pre>

**Comment by marble** [comment]
Ah, sorry, probably my fault. I just saw that I need to "sudo ansible-galaxy install -r requirements.yml"

**Comment by Tuurlijk** [comment]
ok :-)
