### ISSUE TITLE
Windows Support?

### ISSUE THREAD

**Issue by Norcoen** [Tuurlijk/TYPO3.Homestead#17]
Is it possible to run this on a windows machine?
Ansible isn't available under windows, is it really needed?

**Comment by Tuurlijk** [comment]
Yes, unfortunately it's really needed. I mean, I can choose another config management system and rewrite all the configuration steps to it, but that will take some time. It will have to be a config management solution that runs cross platform. Any suggestions?

**Comment by Norcoen** [comment]
Thanks for the reply. I stumbled upon your project searching for better ways to work on local copies of TYPO3 projects.

I used PuPHPet which uses puppet with other TYPO3 projects, so far it's working fine on windows.
Chef might be an alternative to puppet as far as I can tell.

So I can't really make any good suggestions other than those two I barely know :/

**Comment by pniederlag** [comment]
Hi,as ansible is already available in the box wouldn't it be possible to just execute the ansible provisioning from within the machine?
- Add a small shell script to be used as provisioner that just fetches the requirements from ansible galaxy(runing inside the box)
- Run ansible inside the box

Wouldn't this be an approach to consider?
Other than that: awesome project! :)

**Comment by Tuurlijk** [comment]
That would be neat if that would work. :-) Can you whip up an example?

**Comment by Tuurlijk** [comment]
Current version works on Windows. Project is now pre-built.
