### ISSUE TITLE
Error related to role php-fpm in Ansible

### ISSUE THREAD

**Issue by fabarea** [Tuurlijk/TYPO3.Homestead#2]
I just grabbed a fresh copy, run `vagrant up` and got this error.

<pre>

==> default: Machine booted and ready!
==> default: Checking for guest additions in VM...
==> default: Checking for host entries
==> default: adding to (/etc/hosts) : 192.168.12.12  typo3.homestead  # VAGRANT: 03bc63cdca6dc505f74f2920ee22e623 (default) / 3a8e718d-f110-4d1f-9d1c-6a5c97394069
==> default: adding to (/etc/hosts) : 192.168.12.12  4.5.typo3.cms  # VAGRANT: 03bc63cdca6dc505f74f2920ee22e623 (default) / 3a8e718d-f110-4d1f-9d1c-6a5c97394069
==> default: adding to (/etc/hosts) : 192.168.12.12  4.5.39.typo3.cms  # VAGRANT: 03bc63cdca6dc505f74f2920ee22e623 (default) / 3a8e718d-f110-4d1f-9d1c-6a5c97394069
==> default: adding to (/etc/hosts) : 192.168.12.12  6.2.typo3.cms  # VAGRANT: 03bc63cdca6dc505f74f2920ee22e623 (default) / 3a8e718d-f110-4d1f-9d1c-6a5c97394069
==> default: adding to (/etc/hosts) : 192.168.12.12  6.2.9.typo3.cms  # VAGRANT: 03bc63cdca6dc505f74f2920ee22e623 (default) / 3a8e718d-f110-4d1f-9d1c-6a5c97394069
==> default: adding to (/etc/hosts) : 192.168.12.12  7.0.typo3.cms  # VAGRANT: 03bc63cdca6dc505f74f2920ee22e623 (default) / 3a8e718d-f110-4d1f-9d1c-6a5c97394069
==> default: adding to (/etc/hosts) : 192.168.12.12  7.0.2.typo3.cms  # VAGRANT: 03bc63cdca6dc505f74f2920ee22e623 (default) / 3a8e718d-f110-4d1f-9d1c-6a5c97394069
==> default: adding to (/etc/hosts) : 192.168.12.12  1.2.typo3.neos  # VAGRANT: 03bc63cdca6dc505f74f2920ee22e623 (default) / 3a8e718d-f110-4d1f-9d1c-6a5c97394069
==> default: adding to (/etc/hosts) : 192.168.12.12  dev-master.typo3.neos  # VAGRANT: 03bc63cdca6dc505f74f2920ee22e623 (default) / 3a8e718d-f110-4d1f-9d1c-6a5c97394069
==> default: Setting hostname...
==> default: Configuring and enabling network interfaces...
==> default: Exporting NFS shared folders...
==> default: Preparing to edit /etc/exports. Administrator privileges will be required...
==> default: Mounting NFS shared folders...
==> default: Running provisioner: ansible...
PYTHONUNBUFFERED=1 ANSIBLE_FORCE_COLOR=true ANSIBLE_HOST_KEY_CHECKING=false ANSIBLE_SSH_ARGS='-o UserKnownHostsFile=/dev/null -o ForwardAgent=yes -o ControlMaster=auto -o ControlPersist=60s' ansible-playbook --private-key=/Users/fudriot/Temporary/TYPO3.Homestead/.vagrant/machines/default/virtualbox/private_key --user=vagrant --connection=ssh --limit='all' --inventory-file=/Users/fudriot/Temporary/TYPO3.Homestead/.vagrant/provisioners/ansible/inventory --extra-vars={"ansible_ssh_user":"vagrant","hostname":"typo3.homestead"} site.yml
ERROR: cannot find role in /Users/fudriot/Temporary/TYPO3.Homestead/roles/nbz4live.php-fpm or /Users/fudriot/Temporary/TYPO3.Homestead/nbz4live.php-fpm or /usr/local/etc/ansible/roles/nbz4live.php-fpm
Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.
</pre>

**Comment by Tuurlijk** [comment]
```
sudo ansible-galaxy install -r requirements.yml
```

Seems to be the step you missed here.

**Comment by fabarea** [comment]
My fault, was too in hurry and didn't read to the end...
