### ISSUE TITLE
Composer and SNI certificates

### ISSUE THREAD

**Issue by jozefspisiak** [Tuurlijk/TYPO3.Homestead#22]
Since yesterday get.typo3.org migrated to cloudflare SNI certificates, therefore on composer update there is an error:

 [Composer\Downloader\TransportException]  
  The "https://get.typo3.org/json" file could not be downloaded: Peer certificate CN=`ssl340684.cloudflaressl.com' did not match expected CN=`get.typo3.org'  
  Failed to enable crypto  
  failed to open stream: operation failed 

I did try to run apt-get upgrade on the open SSL components on the machine, but it didn't help. Any idea how this could be solved?

**Comment by Tuurlijk** [comment]
Can you 'renamen / move' the ~/.composer directory? Does that help composer to fetch fresh cert info?

**Comment by Tuurlijk** [comment]
Does this solve your problem? https://github.com/composer/composer/issues/2798#issuecomment-68200214

In php.ini

curl.cainfo=/etc/ssl/certs/ca-certificates.crt
openssl.cafile=/etc/ssl/certs/ca-certificates.crt

**Comment by Tuurlijk** [comment]
I get the exact same error in the Atlas box build. Testing if this solves the issue.

**Comment by Tuurlijk** [comment]
No dice

```
Installing dependencies
- Installing typo3/cms-composer-installers (1.1.4) Downloading
- Installing helhum/class-alias-loader (1.1.5) Downloading
- Installing doctrine/instantiator (1.0.5) Downloading

[RuntimeException] The \"https://get.typo3.org/json\" file could not be downloaded: Peer certificate CN=`ssl340684.cloudflaressl.com' did not match expected CN=`get.typo3.org' Failed to enable crypto failed to open stream: operation failed [Composer\\Downloader\\TransportException] The \"https://get.typo3.org/json\" file could not be downloaded: Peer certificate CN=`ssl340684.cloudflaressl.com' did not match expected CN=`get.typo3.org' Failed to enable crypto failed to open stream: operation failed install
```

**Comment by jozefspisiak** [comment]
yes, I believe this has nothing to do with how the certificates are being read, but with how they are being verified. Composer must be using some own implementation of openSSL, since according to documentation openssl should support these certificates from version 0.9.8f and on my machine has currently 1.0,1f

**Comment by Tuurlijk** [comment]
Here is a fix. As root:

`curl -sS https://getcomposer.org/installer | php -- --version=1.0.0-alpha11`

And then copy that composer.phar over /usr/local/bin/composer

**Comment by jozefspisiak** [comment]
Works. Thank you.
