### ISSUE TITLE
Running dev-master unit tests using web ui fails

### ISSUE THREAD

**Issue by stmllr** [Tuurlijk/TYPO3.Homestead#24]
Requesting http://local.typo3.org/review.php ends up with:

Unit tests on dev-master.local.typo3.org
sh: 1: /usr/local/phpbrew/php/php-7.0.3/bin/php: not found

Indeed there is not such directory php-7.0.3 in /usr/local/phpbrew/php/

Michiel/Development (virtualbox, 0.2.47)

**Comment by Tuurlijk** [comment]
Ack.

This was fixed here: https://github.com/MaxServ/TYPO3.CMS.Local/commit/458f2029c03a593b4d4129e20b9a1d84ca664db5

Please do a `git pull` in `/var/www/local.typo3.org`.

Or, if you also want http2 goodness . . . . `vagrant destroy; vagrant box update; vagrant up`.

Take care to backup any stuff you created on the box before destroying ;-)

**Comment by stmllr** [comment]
Please reopen, new errors after executing:

```
cd /var/www/local.typo3.org
git pull
cd /var/www/dev-master.local.typo3.org/typo3_src-master
git pull
```

```
Unit tests on dev-master.local.typo3.org
PHP Fatal error:  Cannot redeclare xdebug() (previously declared in /var/www/typo3_src/typo3_src-master/typo3/sysext/core/Resources/PHP/GlobalDebugFunctions.php:3) in /var/www/typo3_src/typo3_src-master/typo3/sysext/core/Resources/PHP/GlobalDebugFunctions.php on line 11

Fatal error: Cannot redeclare xdebug() (previously declared in /var/www/typo3_src/typo3_src-master/typo3/sysext/core/Resources/PHP/GlobalDebugFunctions.php:3) in /var/www/typo3_src/typo3_src-master/typo3/sysext/core/Resources/PHP/GlobalDebugFunctions.php on line 11

```

**Comment by Tuurlijk** [comment]
I'm sorry. This path does not look like a 'stock' Homestead resource. You may be using shared folders. The problem code may lie in there. It's not Homesteads fault I think.

Please try to execute a manual `php ./bin/phpunit -c typo3_src/typo3/sysext/core/Build/UnitTests.xml` and see what that gives you.
