### ISSUE TITLE
Include TYPO3 v8 in the setup

### ISSUE THREAD

**Issue by ulrikkold** [Tuurlijk/TYPO3.Homestead#29]
This is almost too obvious to ask for it :-)

**Comment by Tuurlijk** [comment]
I'm trying :-)

**Comment by ulrikkold** [comment]
I am sure you are 😊

Den tor. 24. mar. 2016 08.06 skrev Michiel Roos notifications@github.com:

**Comment by Tuurlijk** [comment]
Build is failing because mailcatcher requires ruby 1.9.3 and some module that is required by mailcatcher reqiures ruby 2.0 . . . _sigh_

**Comment by Tuurlijk** [comment]
I might just disable mailcatcher.

**Comment by ulrikkold** [comment]
That is a possible solution.

But how can that catch-22 situation occur? Can you exclude the module?

**Comment by Tuurlijk** [comment]
I now use https://github.com/mailhog/MailHog. https://github.com/Tuurlijk/TYPO3.Packer/commit/845e9e2fd37697dea24d010a66e393e7dcafe048

V8 is in

**Comment by ulrikkold** [comment]
Good work. It also seems the move to MailHog is a smart one ☺

Den fre. 25. mar. 2016 15.26 skrev Michiel Roos notifications@github.com:
