### ISSUE TITLE
[vagrant box] review and dev-master

### ISSUE THREAD

**Issue by nimayneb** [Tuurlijk/TYPO3.Homestead#32]
Composer installation.
Vagrant up.

First the vagrant box has empty databases for "review_local_typo3_org" and "dev-master_local_typo3_org". Okay, only import it from the others...

When i update my sites by "local.typo3.org" i run into exceptions like this:

```
Uncaught Exception in TYPO3 CMS Argument 1 passed to TYPO3\CMS\Core\Package\PackageManager::registerPackagesFromConfiguration() must be of the type array, none given, called in /var/www/dev-master.local.typo3.org/typo3conf/ext/typo3_console/Classes/Package/UncachedPackageManager.php on line 70
thrown in file ext/core/Classes/Package/PackageManager.php
in line 391

#0 Helhum\Typo3Console\Error\ExceptionHandler::handleException()
   /var/www/dev-master.local.typo3.org/typo3conf/ext/typo3_console/Classes/Error/ExceptionHandler.php:0
```

**Comment by Tuurlijk** [comment]
Thank you for the report.

I have updated the boxes yesterday. You can now do a `vagrant box update` to fetch the latest version. If you already have a box running, you can destroy it ( if you don't have anything important on it ). `vagrant destroy` and then `vagrant up`.

**Comment by jozefspisiak** [comment]
This problem still persist in the latest 0.3.0 version of your box. Both databases are empty and typo3_console 1.3.0 is actually broken with the latest TYPO3 core. You need to switch it to the 3.0.0 in order to get those 2 servers to update. Running on latest Os X, Virtualbox and Vagrant, when testing it.

**Comment by jozefspisiak** [comment]
Nevermind. Destroyed it again and it works now. Must be when upgrading boxes, the database disappears or something.

**Comment by Tuurlijk** [comment]
Great! ;-)

**Comment by Tuurlijk** [comment]
When doing a `vagrant destroy`, it dumps the whole box. A `vagrant up` will re-create a new box from the 0.3.0 version you just downloaded. This new box contains all the new stuff with working setups etc. I use typo3_console 3.1 now for the 8.x installs: https://github.com/Tuurlijk/TYPO3.Packer/blob/master/ansible/roles/typo3/templates/cms/composer.json

**Comment by Tuurlijk** [comment]
It is confusing that `vagrant box update` does not in fact update the existing box, but merely updates the 'template' so to speak.
