### ISSUE TITLE
TYPO3 CMS backend login not possible

### ISSUE THREAD

**Issue by josefglatz** [Tuurlijk/TYPO3.Homestead#4]
Hi,
I've tried your homestead vagrant box. Provisioning is working without failures. After installing eg 6.2 or 7.0.2 I could not login in the backend. I always get an Error:
`#1: PHP Warning: session_start(): open(/var/lib/php5/sess_ean28u4ku4v470p0ae64dj9b54, O_RDWR) failed: Permission denied (13) in /var/www/sources/cms/TYPO3_6-2/typo3/sysext/backend/Classes/Controller/LoginController.php line 147`

I've tried it both with virtualbox and vmware_fusion.

**Comment by Tuurlijk** [comment]
That's weird. What php version do you use? The stock ubuntu stores the sessions in /var/lib/php5/ and the ppa php version stores them in /var/lib/php5/sessions. I just ripped out the ppa php version today in the master branch. I adjusted the ramdisk code accordingly. Am building a fresh machine now.

**Comment by Tuurlijk** [comment]
Can you please try with a clean machine? There have been quite some changes including a reversion to stock ubuntu php (awaiting phpbrew build config support) and the introduction of the magical *.local.typo3.org wildcard domain - linked to a new local ip. A `vagrant destroy` and `vagrant up` should do it.

**Comment by josefglatz** [comment]
Thx, works now.
