### ISSUE TITLE
mariadb root user credential

### ISSUE THREAD

**Issue by luberti** [Tuurlijk/TYPO3.Homestead#40]
The readme states that db credentials are in 

roles/mariadb/vars/main.yml

but I cannot find this file

**Comment by Tuurlijk** [comment]
Nice catch!

Updated that to:

MySQL can be accessed as `root` or `typo3`. In both cases the password is `supersecret`.

**Comment by luberti** [comment]
actually not, only way I found to connect with rights to create a db was using sudo mysql
