### ISSUE TITLE
root user password for database

### ISSUE THREAD

**Issue by aWuttig** [Tuurlijk/TYPO3.Homestead#43]
You described that the root user pw for database login is "supersecret". When i try this it doesn`t work.

**Comment by Tuurlijk** [comment]
`mysql -u root -p`

Should work if you're on the box.

Please describe the exact steps you are taking to login.

**Comment by aWuttig** [comment]
I clone the git repo and then i do vagrant up on my windows 10 host machine.

After this i login via ssh und try: 

$ mysql -u root -p
Enter password:
ERROR 1698 (28000): Access denied for user 'root'@'localhost'

i use "supersecret" as password.

**Comment by Tuurlijk** [comment]
What happens if you run `vagrant box outdated` from the Homestead dir?

**Comment by aWuttig** [comment]
vagrant box outdated 
Checking if box 'Michiel/Development' is up to date...

and thats all.

**Comment by Tuurlijk** [comment]
Strange. Apparently you can only login using the root account as the root user. I updated the readme.

Please try to `sudo su -` and then just `mysql` should do.

**Comment by aWuttig** [comment]
Ah okay. Thank u

Am 25.07.2017 11:22 schrieb "ℳichiel ℛoos" <notifications@github.com>:

Strange. Apparently you can only login using the root account as the root
user. I updated the readme.

Please try to sudo su - and then just mysql should do.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/Tuurlijk/TYPO3.Homestead/issues/43#issuecomment-317680660>,
or mute the thread
