### ISSUE TITLE
Move private variables into non-versioned files

### ISSUE THREAD

**Issue by stucki** [Tuurlijk/TYPO3.Homestead#6]
Several settings should be moved out of the Git repository, otherwise they will also remain as differences compared to the upstream repository:
- Configuration/typo3.yml: typo3_org_username
- Configuration/vagrant.yml: synced_folders

I suggest to create a new file Configuration/overrides.yml which is not under Git version control. Add Configuration/overrides.yml.template to Git so it can be copied and adjusted easily.

**Comment by Tuurlijk** [comment]
Hmm, ok. I think it's best to have a 'Defaults' folder that is copied over into the Configuration folder on first run.

**Comment by Tuurlijk** [comment]
Solved with https://github.com/Tuurlijk/TYPO3.Homestead/commit/7c8d485709e1e5edac9a74b29ffb0ccd85411d01
