### ISSUE TITLE
Wrong file/folder permissions of var/www content after vagrant up

### ISSUE THREAD

**Issue by fsaris** [Tuurlijk/TYPO3.Homestead#9]
After just cloning the vagrant box and running `vagrant up` the provisioning of the vagrant box fails due to permission problems.

The cloning of the TYPO3 sources is done as root but the permissions/owner ship should be set to the the vagrant user. Or maybe even to the  www-data group

**Comment by Tuurlijk** [comment]
Solved in: https://github.com/Tuurlijk/TYPO3.Homestead/commit/97b927ff50f756403cf793db6ba445845e03d4c9
